name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:


  lin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - mcode
          - llvm
          - gcc
    name: '🐧 Ubuntu · ${{ matrix.backend }}'
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v3
        with:
          path: OsvvmLibraries
          submodules: recursive

      - name: '⚙️ Setup GHDL'
        uses: ghdl/setup-ghdl-ci@master
        with:
          backend: ${{ matrix.backend }}

      - name: '🛠️ Install tcl'
        run: |
          sudo apt update -qq
          sudo apt install -y tcl tcllib

      - name: '🚧 Run tests'
        run: tclsh ./OsvvmLibraries/.github/test.tcl

      - name: '📤 Upload artifact: logs'
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-ghdl-${{ matrix.backend }}-log
          path: |
            *.log
            *.yml
            *.html
            *.xml
            reports/*.html
            reports/**/*.html
            logs/**/*.*
          if-no-files-found: error
        

  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          #- {icon: '🟪', msys: 'MINGW32', pkg: "llvm"  } ! Not yet functional
          - {icon: '🟦', msys: 'MINGW64', pkg: 'llvm'  }
          - {icon: '🟨', msys: 'UCRT64',  pkg: 'llvm'  } #! Experimental
          - {icon: '🟪', msys: 'MINGW32', pkg: 'mcode' }
          #- {icon: '🟦', msys: 'MINGW64', pkg: "mcode" } ! Simulation with mcode is not yet supported on win64
          #- {icon: '🟨', msys: 'UCRT64',  pkg: "mcode" } ! Experimental; Simulation with mcode is not yet supported on win64
    name: '${{ matrix.icon }} ${{ matrix.msys }} · ${{ matrix.pkg }}'
    defaults:
      run:
        shell: msys2 {0}
    steps:

      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msys }}
          update: true
          install: git
          pacboy: tcl:p tcllib:p make:p python3:p

      - name: '🧰 Checkout'
        uses: actions/checkout@v3
        with:
          path: OsvvmLibraries
          submodules: recursive

      - name: '⚙️ Setup GHDL'
        uses: ghdl/setup-ghdl-ci@master
        with:
          backend: ${{ matrix.pkg }}

      - name: '🚧 Run tests'
        run: tclsh ./OsvvmLibraries/.github/test.tcl

      - name: '📤 Upload artifact: logs'
        uses: actions/upload-artifact@v3
        with:
          name: msys2-ghdl-${{ matrix.pkg }}-${{ matrix.msys }}-log
          path: |
            *.log
            *.yml
            *.html
            *.xml
            reports/*.html
            reports/**/*.html
            logs/**/*.*
          if-no-files-found: error


  publish-test-results:
    if: always()
    needs: [lin, win]
    runs-on: ubuntu-latest
    name: 📊 Publish Unit Tests Results
    steps:

      - name: ⏬ Checkout repository
        uses: actions/checkout@v3

      - name: '📥 Download artifact: package'
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: 📊 Publish Unit Test Results
        uses: dorny/test-reporter@v1
        with:
          name: OSVVM VC Regression Results
          path: artifacts/**/*.xml
          reporter: java-junit
